### ISSUE TITLE
Firefox webdriver crashes when launched

### ISSUE THREAD

**Issue by TychosNose** [MicrosoftEdge/BrowserEfficiencyTest#20]
Issue is with Firefox 47.0 and Webdriver 2.53
[selenium-2-53-not-working-on-firefox-47](http://stackoverflow.com/questions/37693106/selenium-2-53-not-working-on-firefox-47)

**Comment by nolanlawson** [comment]
Yeah, we technically used 47.0.1 for the WebDriver tests, not 47.0, for exactly the reason you cite. Unfortunately there seems to be a lot of churn with Marionette/geckodriver/etc. which is why we had to pin to a particular version.

Please reopen if this doesn't answer your question! :smiley:
